name: ave_life  # Package name in lowercase
description: "A new Flutter project for Ave Life, a health awareness application."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

# Versioning information
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3        # For making API requests
  provider: ^5.0.0     # For state management
  cupertino_icons: ^1.0.8  # iOS style icons
  avatar_glow: ^2.0.0   # For avatar glow effect
  firebase_core: ^2.14.0  # Ensure it's compatible with firebase_auth
  firebase_auth: ^4.16.0   # Downgrade to ensure compatibility
  google_sign_in: ^6.1.0 # For Google sign-in
  flutter_facebook_auth: ^5.0.0 # For Facebook sign-in

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Recommended lints for good coding practices

# Flutter specific configurations
flutter:
  uses-material-design: true  # Ensure Material Icons are included

  # Assets
  assets:
    - assets/healthy_lifestyle.png  # Correctly references your image file
    - assets/comic_background.png  # Include your comic background image here
    # Add more images or assets as needed

  # Uncomment and add custom fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
